// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1XiLnYJMsZfqX7bwhLHzcPGK94Mt4aFI',
    appId: '1:725373217006:web:377dd80b6aeeff772b2bff',
    messagingSenderId: '725373217006',
    projectId: 'fir-map-41f62',
    authDomain: 'fir-map-41f62.firebaseapp.com',
    storageBucket: 'fir-map-41f62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrW-yx7ts5UOmLi-25TFYsUN-mWovOEIU',
    appId: '1:725373217006:android:f5efd816000db58d2b2bff',
    messagingSenderId: '725373217006',
    projectId: 'fir-map-41f62',
    storageBucket: 'fir-map-41f62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhKQpbAUlOgZw-nl4cD-bbZlhX-XMXtw',
    appId: '1:725373217006:ios:e582734d1f1f63b02b2bff',
    messagingSenderId: '725373217006',
    projectId: 'fir-map-41f62',
    storageBucket: 'fir-map-41f62.appspot.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhKQpbAUlOgZw-nl4cD-bbZlhX-XMXtw',
    appId: '1:725373217006:ios:e582734d1f1f63b02b2bff',
    messagingSenderId: '725373217006',
    projectId: 'fir-map-41f62',
    storageBucket: 'fir-map-41f62.appspot.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1XiLnYJMsZfqX7bwhLHzcPGK94Mt4aFI',
    appId: '1:725373217006:web:87ffe6bf93cb43ab2b2bff',
    messagingSenderId: '725373217006',
    projectId: 'fir-map-41f62',
    authDomain: 'fir-map-41f62.firebaseapp.com',
    storageBucket: 'fir-map-41f62.appspot.com',
  );
}
